name: FirsteProjectFlutter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.0
  flutter_swiper: 1.1.6
  flutter_staggered_grid_view: ^0.4.0
  rubber: ^1.0.0
  pin_code_text_field: ^1.8.0
  country_code_picker: ^2.0.1
  http: ^0.12.0
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  numberpicker: ^2.1.1
  flare_splash_screen: ^4.0.0
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.5
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0
  badges: ^2.0.1
  pull_to_refresh: ^2.0.0
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/promotional/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
